import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import AuthGurad from "./authGurad";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster position="top-right" />
          <AuthGurad>{children}</AuthGurad>
        </Providers>
      </body>
    </html>
  );
}
